### ISSUE TITLE
Running lerna commands with 1.0.0 gives: Error: Cannot find module 'import-local'

### ISSUE THREAD

**Issue by brammitch** [ghiscoding/lerna-lite#58]
## Your Environment

| Executable        | Version |
| ----------------- | ------- |
| `lerna --version` | unable to run command |
| `npm --version` | 8.5.4 |
| `yarn --version` | not installed |
| `node --version` | 16.14.0 |

| OS   | Version |
| ---- | ------- |
| Windows 11 | 21H2 |
| WSL2/Ubuntu | 21.04 |

### Describe the Bug

Running any of the lerna commands with 1.0.0 installed gives `Error: Cannot find module 'import-local'`. Using ws-roller and ws-runner worked fine in 0.3.7.

### Steps to Reproduce (for bugs)

1. Make a new project `npm init`
2. Install deps `npm i @lerna-lite/cli @lerna-lite/run`
3. `lerna version` -> Error: Cannot find module 'import-local'

<details><summary>lerna.json</summary><p>

```json
{
  "packages": ["packages/*"],
  "version": "1.0.3",
  "npmClient": "npm",
  "useWorkspaces": true,
  "command": {
    "version": {
      "allowBranch": "main",
      "conventionalCommits": true,
      "message": "chore(release): publish"
    }
  }
}
```
</p></details>

### Expected Behavior

The lerna commands should function the same way they did when it was `ws-roller` and `ws-runner`

### Current Behavior

```node
$ lerna version
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'import-local'
Require stack:
- /home/brando/.nvs/node/16.14.0/x64/lib/node_modules/@lerna-lite/cli/dist/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/brando/.nvs/node/16.14.0/x64/lib/node_modules/@lerna-lite/cli/dist/cli.js:8:40)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/brando/.nvs/node/16.14.0/x64/lib/node_modules/@lerna-lite/cli/dist/cli.js'
  ]
}
```

**Comment by ghiscoding** [comment]
looks like I forgot to add it to the CLI [package.json](https://github.com/ghiscoding/lerna-lite/blob/main/packages/cli/package.json), would you like to do a Pull Request? I can push a patch release later today

**Comment by brammitch** [comment]
Sure, I'll take a look at it right now.

**Comment by ghiscoding** [comment]
pushed a patch release over lunch, thanks for the feedback and PR
